'use strict';

angular.module("BBDocsApp").controller("ListCtrl", function($scope) {
  $scope.brands = [
    {
      name: "Services",
      list: [
        "37signals",
        "amazon",
        "aol",
        "baidu",
        "delicious",
        "digg",
        "disqus",
        "docomo",
        "dwolla",
        "eventbrite",
        "eventful",
        "evernote",
        "exact",
        "fitbit",
        "gmail",
        "google",
        "grooveshark",
        "instapaper",
        "intensedebate",
        "itunes",
        "lanyrd",
        "logmein",
        "miicard",
        "ninetyninedesigns",
        "opentable",
        "paypal",
        "pinboard",
        "planningcenter",
        "pocket",
        "salesforce",
        "scribd",
        "shopify",
        "songkick",
        "spotify",
        "statusnet",
        "stripe",
        "stumbleupon",
        "yahoo",
        "yandex",
        "yelp",
      ],
    },
    {
      name: "Content sites",
      list: [
        "500px",
        "wikipedia",
        "wordpress",
        "ycombinator"
      ]
    },
    {
      name: "Misc",
      list: [
        "bitcoin",
        "box",
        "cloudapp",
        "creativecommons",
        "dropbox",
        "html5",
        "ie",
        "podcast",
        "rss",
        "skype",
        "steam",
        "windows",
      ],
    },
    {
      name: "Stores",
      list: [
        "android",
        "appstore",
        "googleplay",
        "macstore",
      ],
    },
    {
      name: "Socials",
      list: [
        "appnet",
        "blogger",
        "bitbucket",
        "dribbble",
        "facebook",
        "flattr",
        "flickr",
        "foursquare",
        "github",
        "googleplus",
        "gowalla",
        "instagram",
        "klout",
        "lastfm",
        "line",
        "linkedin",
        "meetup",
        "myspace",
        "pinterest",
        "plurk",
        "quora",
        "reddit",
        "renren",
        "smashing",
        "soundcloud",
        "stackoverflow",
        "tumblr",
        "twitter",
        "viadeo",
        "vimeo",
        "vk",
        "weibo",
        "xing",
        "yammer",
        "youtube",
      ]
    },
    {
      name: "Games",
      list: [
        "csgo",
        "dota2",
        "gm",
        "lol",
        "minecraft",
        "quake",
        "tf2",
        "wot"
      ]
    }
  ];

  console.log( $scope.brands );
});